title: Frogware
description: A Minecraft utility mod for anarchy servers
show_downloads: false
google_analytics: UA-157505961-1
github:
  repository_url: https://github.com/XZRC/FrogWare
  website_url: https://github.com/XZRC/FrogWare
  jar_url: https://github.com/XZRC/FrogWare/releases/download/1.0/Frogware-1.0-Release.jar
  zip_url: https://github.com/XZRC/FrogWare/releases/download/1.0/Frogware-1.0-Release.jar
  tar.gz_url: https://github.com/XZRC/FrogWare/releases/download/1.0/Frogware-1.0-Release.jar
cur_ver: v1.0
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - liquid
